apiVersion: v1
kind: Service
metadata:
  labels:
    app: valheim-server
  name: valheim-server
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
    - name: server1
      port: 2456
      protocol: UDP
      targetPort: 2456
    - name: server2
      port: 2457
      protocol: UDP
      targetPort: 2457
    - name: server3
      port: 2458
      protocol: UDP
      targetPort: 2458
  selector:
    app: valheim-server
  type: LoadBalancer
